"""Shared tuning in pixels and seconds; the simulation grid remains 8 pixels."""
CELL = 8
SCALE = 5
MACRO = CELL * SCALE
SCREEN_W, SCREEN_H = 960, 640
FPS = 60
PRECISE_FRAME_PACING = True
MAX_FRAME_DT = 0.1
PHYSICS_HZ = 120
FLUID_HZ = 25
GRAVITY = 1100.0
MAX_FALL_SPEED = 560.0
MOVE_SPEED = 176.0
JUMP_SPEED = 340.0
SWIM_SPEED = 130.0
LADDER_JUMP_GRACE = 0.18
PLAYER_SIZE = 32
DIG_RADIUS = 3
DIG_REACH = 18
ENEMY_SIGHT_RANGE = 360
ENEMY_FIRE_INTERVAL = 1.25
PROJECTILE_SPEED = 240.0
PROJECTILE_DAMAGE = 20
PROJECTILE_RADIUS = 4
CHUNK_CELLS = 40
MAX_PARTICLES = 150
MOTE_LIMIT = 18          # drifting dust specks in lantern light
EMBER_INTERVAL = 0.11    # seconds between embers from visible lava
CAMERA_FOLLOW = 14.0     # 1/s; higher follows tighter (no input delay)
SHAKE_DECAY = 1.6        # trauma lost per second
WATER_FLOW_RATE = 1.0
LAVA_FLOW_RATE = 0.22
MIN_FLOW_UNITS = 8  # 8/1024 cell; below a visible quarter-pixel surface change.
REACTION_DURATION = 0.48
REACTION_INTERVAL = 0.075
REACTION_LIMIT = 2048
REACTION_STEP_LIMIT = 128
